### ISSUE TITLE
BB design facility becomes unresponsive after adding a Super Column to a Super Table 

### ISSUE THREAD

**Issue by kpturner** [poirazis/bb-component-SuperTable#10]
I followed the instructions to add a "super table" plug-in at the bottom of this page
https://docs.budibase.com/docs/table

I added a super table within a Data Provider
I added a super column to the table
I added a second column and it appeared to add it as a child to the first column rather than the table.

The design page is now unresponsive.

How do I recover?

**Comment by kpturner** [comment]
Ahh -> https://github.com/poirazis/bb-component-SuperTableColumn/issues/5

**Comment by DeadGhost1407** [comment]
This happened to me as well. I deleted the datasource from the data tab of the app. When I switched to the design tab I got an error that the datasource was deleted but the app worked long enough for me to delete the nested column.

Not sure if this will work for you but hope it helps. Another option is exporting the app, open it with a text editor, find the column and delete it, then import the app. Either way, best of luck.

**Comment by kpturner** [comment]
I managed to delete the screen - disappointing to have to start again but at least it's now usable. Thanks

**Comment by raventechnologiesinc** [comment]
I installed SuperTable as well and encountered design page slow and unresposive.
Pages do not update or refresh as before.
Anyone have same experience?

**Comment by raventechnologiesinc** [comment]
I found the trigger that freez the app.  Whenever an ON CLICK event is activated the app does not render completed.  Removed the ONCLICK even thing back to normal.  Design page have to be refreshed to see any changes.  Very sluggish.

**Comment by poirazis** [comment]
The nesting issue has been resolved.
