### ISSUE TITLE
Select one row but UI shows up like selecting all rows

### ISSUE THREAD

**Issue by dungtrantt** [poirazis/bb-component-SuperTable#102]
As below picture, I selected one row but UI shows like I selected all rows
<img width="1066" alt="Screenshot 2024-12-17 at 21 48 04" src="https://github.com/user-attachments/assets/19d7aa8d-be51-4435-8935-a3ac4d4007f6" />

**Comment by jasperfunksmit** [comment]
I have the same problem.

**Comment by poirazis** [comment]
should be fixed in latest push @jasperfunksmit , @dungtrantt

**Comment by dungtrantt** [comment]
@poirazis Thank you. It's good now
