### ISSUE TITLE
{{ Value }} not working in column customization

### ISSUE THREAD

**Issue by arminus** [poirazis/bb-component-SuperTable#72]
BudiBase: 2.29.18, SuperTables: 2.0.24

It seems I can't get the column customization to work at all:

![2024-07-22_132806](https://github.com/user-attachments/assets/d504284e-fac2-463c-b340-b1719058ca9e)

Although the all_day column clearly has a value which shows up in the table by default, using the {{ Value }} binding does not seem to work. (ultimately, I would like to replace a 1 value with "AllDay" and non 1 with "")

Also, I can't figure out how to get to the column values of the clicked row in the on row click action...?

**Comment by poirazis** [comment]
hey @arminus does lower case {{ value }} work ?

**Comment by arminus** [comment]
Nope, preview doesn't show anything for {{ value }} either. Same for return $("Value") or return $("value") in JS.

The strange thing is that the table itself still shows the original column values, even if there's a {{ Value }} defined, but obviously my logic to replace the original values with something else as outlined above doesn't work.

Checked this for different columns of the same table, same result. The table data comes from a DataProvider which in turn calls a REST endpoint.

**Comment by arminus** [comment]
Just tested this with a dummy test app with just one budibase table. Same problem.

**Comment by poirazis** [comment]
hey @arminus 
it doesnt work in the preview, but it works fine for me in previerw / published

**Comment by arminus** [comment]
Ok, one step further. This seems to work with text columns but not with numeric columns. See the attached test app.

![grafik](https://github.com/user-attachments/assets/658f57b5-c296-42ee-9276-d945462a9f33)

[SuperTableTest-export-1721909591558.tar.gz](https://github.com/user-attachments/files/16377356/SuperTableTest-export-1721909591558.tar.gz)

**Comment by arminus** [comment]
Also doesn't seem to work with boolean columns

**Comment by poirazis** [comment]
i have fixed the issue with the number column , will look into the boolean too
try the latest release
2.0.25-alpha

**Comment by arminus** [comment]
Nice, boolean works now too. Spotted something else with 2.0.25-alpha: Custom column labels seem to be ignored, supertable column labels are always the data table column names, event if I set a different label?

**Comment by poirazis** [comment]
fixed in latest push 2.0.26-alpha @arminus !

**Comment by arminus** [comment]
Thanks, that works :-)
