### ISSUE TITLE
How to access  super-table columns values

### ISSUE THREAD

**Issue by seoulaja** [poirazis/bb-component-SuperTable#8]
Hi @poirazis 

Firstly, I would like to say thank you for your great plugins for @budibase. They are very useful and handy for my work!!

I have a question, in super table how I can access other column/cell value?

The case is when I click a "Settings" button on super table it would navigate to other pages which has 2 URL Parameters. This parameter got the value from the data of the table.

Regards,
Seoul

**Comment by poirazis** [comment]
Hey @seoulaja and thank you for your kind words !
You can put components ( any budibase component ) inside the SuperTableColumn and you can then bind to the Cell Value. In your case you can drop a Button / Icon / Link and use the cell value / row id bindings exposed by the Super Table Column to pass on as parameters 

hope this helps !

**Comment by poirazis** [comment]
Hey @seoulaja 

You can use the Row ID to grab any column value from the wrapping dataprovider.
Exposing full row data to each cell would be a performance issue as each super column is a district component.

Hope this helps !

**Comment by seoulaja** [comment]
Hi @poirazis 

Thank you! It works!

For the benefit of other users, here is the solution for me:

```
const a = $("Data Provider.Rows").filter(x => x.ProposalId === $("Settings.Row ID"));
const projectGroupId = helpers.pluck(a,'ProjectGroupId');
return '/proposal-settings/'+$("Settings.Cell Value")+'/'+projectGroupId;
```

cheers
